server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    include /etc/nginx/mime.types;
    absolute_redirect off;
    location /food-macro {
        try_files $uri $uri/ /food-macro/index.html;
    }
}
